apiVersion: apps/v1
kind: Deployment
metadata:
  name:  app-deployment
  labels:
    app:  app-deployment
spec:
  selector:
    matchLabels:
      app: hello-app
  replicas: 1
  template:
    metadata:
      labels:
        app:  hello-app
    spec:
      containers:
      - name:  hello-app
        image:  eduardolatorre/hello-app
      imagePullSecrets:
      - name: regcred