name: Build
on:
  push:
    branches:
      - main
env:
    DOCKER_IMAGE_NAME: hello-app
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Set image version
        run: echo "IMAGE_VERSION=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      - name: Output image details
        run: |
          echo "The new image version to be pushed"
          echo "${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:$IMAGE_VERSION"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:$IMAGE_VERSION
