name: Build
on:
  push:
    branches:
      - main
env:
    DOCKER_USERNAME: eduardolatorre
    DOCKER_IMAGE_NAME: hello-app
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Set image version
        run: |
          echo "image_version=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_OUTPUT
        id: set_image_version

      - name: Print image version
        run: |
          echo The image version is: ${{ steps.set_image_version.outputs.image_version }}
